services:
  backend:
    build:
      context: ./api
      dockerfile: ./Dockerfile.prod
    container_name: api
    env_file:
      - ./api/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.prod
    container_name: frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: unless-stopped

volumes:
  postgres_data:
