services:
  backend:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: api
    env_file:
      - .env
    environment:
      - DATABASE_URL
      - SECRET_KEY
      - DISABLE_COLLECTSTATIC
      - DEVELOPMENT
      - CLIENT_ORIGIN
      - CORS_ALLOWED_ORIGINS
      - CLOUDINARY_URL
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: frontend
    env_file:
      - .env
    environment:
      - REACT_APP_API_URL
    volumes:
      - ./frontend:/app
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: db
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

volumes:
  postgres_data:

